"""comment author

Revision ID: 5f1c118b893f
Revises: d08b3824b39a
Create Date: 2022-09-15 19:31:52.199862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f1c118b893f"
down_revision = "d08b3824b39a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("author", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comment", "author")
    # ### end Alembic commands ###
