"""add mealplan state enum

Revision ID: 931478b39591
Revises: 94f8406aac25
Create Date: 2022-08-09 17:09:57.675282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "931478b39591"
down_revision = "94f8406aac25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mealplan",
        sa.Column(
            "state",
            sa.Enum("open", "bought", "done", name="mealplanstate"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    op.execute("""UPDATE mealplan SET state='open'""")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mealplan") as batch_op:
        batch_op.drop_column("state")
    # ### end Alembic commands ###
