"""optional ingredient to model

Revision ID: 94f8406aac25
Revises: a4ea46e37fd8
Create Date: 2022-07-13 11:33:33.258775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94f8406aac25"
down_revision = "a4ea46e37fd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredient",
        sa.Column("optional", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe_ingredient", "optional")
    # ### end Alembic commands ###
